version: "3.2"
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/task-tracker
    depends_on:
     - postgres_db_container
    environment:
     - DEBUG=false
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}
     - DB_HOST=postgres_db_container
     - DB_PORT=5432
  postgres_db_container:
    restart: "always"
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./init_db_scripts:/docker-entrypoint-initdb.d
#      Please, do not remove empty `pgdata` folder!
      - ./pgdata:/var/lib/postgresql/data
    labels:
      description: "Postgresql Database"
      service: "postgresql"
    networks:
     - default

    environment:
      - DEBUG=false
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME:?DB_NAME not specified}
volumes:
  postgres_db_container: