version: "3.2"
services:
  web:
    build: .
    ports:
     - "5000:5000"
  postgres:
    restart: "always"
    image: postgres:11-alpine
    ports:
    - "5432:5432"
    volumes:
    - ./init_db_scripts/1init.sql:/docker-entrypoint-initdb.d/1init.sql
    - ./init_db_scripts/2insert.sql:/docker-entrypoint-initdb.d/2insert.sql

#      Below is volume for postgres DB, so we do not need to run init scripts each
#      time when we do `docker-compose up`.
#      But for now, we skip it. The reason is - not stable structure of DB.
#      Please, do not remove empty `pgdata` folder!
#    - ./pgdata:/var/lib/postgresql/data
    environment:
    - DEBUG=false
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=mypassword
    - POSTGRES_DB=task_tracker
volumes:
  pgdata: