"""Create TicketProgressStatus Enum and Ticket table

Revision ID: 41c37d463352
Revises: 08da4446aef6
Create Date: 2019-10-18 17:49:28.391290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import app

revision = '41c37d463352'
down_revision = '08da4446aef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_of_creation', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('assignee', sa.Integer(), nullable=True),
    sa.Column('status',
              sa.Enum(
                  'open', 'inProgress', 'review', 'test', 'closed', name='ticketProgressStatus'
              ),
              default='open',
              nullable=True),
    sa.CheckConstraint("title <> ''", name='valid_ticket'),
    sa.ForeignKeyConstraint(['assignee'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['dashboard_id'], ['Dashboards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'creator_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tickets')
    # ### end Alembic commands ###
