"""empty message

Revision ID: a22b9033a38d
Revises: f005ae29b85e
Create Date: 2020-01-19 19:54:38.184938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a22b9033a38d'
down_revision = 'f005ae29b85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DashboardToUser')
    op.add_column('Tickets', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.drop_constraint('Tickets_assignee_fkey', 'Tickets', type_='foreignkey')
    op.create_foreign_key(None, 'Tickets', 'Users', ['assignee_id'], ['id'])
    op.drop_column('Tickets', 'assignee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tickets', sa.Column('assignee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Tickets', type_='foreignkey')
    op.create_foreign_key('Tickets_assignee_fkey', 'Tickets', 'Users', ['assignee'], ['id'])
    op.drop_column('Tickets', 'assignee_id')
    op.create_table('DashboardToUser',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"DashboardToUser_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'write', 'read', name='userRole'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['Dashboards.id'], name='DashboardToUser_dashboard_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='DashboardToUser_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='DashboardToUser_pkey'),
    sa.UniqueConstraint('dashboard_id', 'user_id', name='DashboardToUser_dashboard_id_user_id_key')
    )
    # ### end Alembic commands ###
