"""ADD FK to the DashboardToUser table

Revision ID: decdd45ef4ec
Revises: eecaaf08a157
Create Date: 2019-10-18 18:32:16.712205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decdd45ef4ec'
down_revision = 'eecaaf08a157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'DashboardToUser', 'Dashboards', ['dashboard_id'], ['id'])
    op.create_foreign_key(None, 'DashboardToUser', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DashboardToUser', type_='foreignkey')
    op.drop_constraint(None, 'DashboardToUser', type_='foreignkey')
    # ### end Alembic commands ###
