"""update Ticket Table

Revision ID: f005ae29b85e
Revises: decdd45ef4ec
Create Date: 2019-10-19 12:51:00.657428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f005ae29b85e'
down_revision = 'decdd45ef4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Tickets_dashboard_id_creator_id_key', 'Tickets', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Tickets_dashboard_id_creator_id_key', 'Tickets', ['dashboard_id', 'creator_id'])
    # ### end Alembic commands ###
